name: C/C++ CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2
    - name: Setup MSYS2
      # You may pin to the exact commit or the version.
      # uses: msys2/setup-msys2@fa138fa56e2558760b9f2205135313c7345c5f3f
      uses: msys2/setup-msys2@v2
      with:
        # Variant of the environment to set by default: MSYS, MINGW32, MINGW64, UCRT64, CLANG32 or CLANG64
        #msystem: # optional, default is MINGW64
        # Default value for MSYS2_PATH_TYPE environment variable: strict, inherit or minimal
        #path-type: # optional, default is minimal
        # Update MSYS2 installation through pacman
        #update: # optional
        # After installation and/or update, install additional packages through pacman
        install: gcc make
        # After installation and/or update, install additional packages through pacboy
        #pacboy: # optional
        # Retrieve and extract base installation from upstream GitHub Releases
        #release: # optional, default is true
        # Where to install MSYS2
        #location: # optional, default is RUNNER_TEMP
        # What to do when run on an incompatible runner: fatal, warn
        #platform-check-severity: # optional, default is fatal
    - run: gcc -v
    - run: ./scripts/build_platform.sh
    - run: file ./build/platform
    - run: ./platform
